version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: vocab_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: vocab
      POSTGRES_USER: vocab
      POSTGRES_PASSWORD: vocab
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
